apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop
  labels: 
    project: roboshop
    environment: dev
    purpose: debug
spec: 
  containers:
  - name: debug #container name
    image: vijayavamsi/debug:4.0.0 #by default if will get from docker hub